version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: meupet_user
      POSTGRES_PASSWORD: G96l207x0122m@
      POSTGRES_DB: meupet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
